import json
import os
import time
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from urllib.parse import urlparse, parse_qs

import typer

from opensurity.identity.base import Identity
from opensurity.identity.level1 import Level1Identity
from opensurity.manifest import AgentManifest, Capability, TrustInfo
from opensurity.log.store import TrustLogStore
from opensurity.registry.local import LocalRegistry

app = typer.Typer(help="OpenSurity CLI")
registry_app = typer.Typer(help="Registry commands")
log_app = typer.Typer(help="Log commands")
identity_app = typer.Typer(help="Identity commands")

app.add_typer(registry_app, name="registry")
app.add_typer(log_app, name="log")
app.add_typer(identity_app, name="identity")


@app.command()
def init(
    name: str = typer.Option(..., help="Name of the agent"),
    framework: str = typer.Option("custom", help="Framework (langgraph, crewai, autogen, custom)")
):
    """Initializes a new OpenSurity agent in the current directory."""
    start_time = time.time()
    
    # 1. Generate L1 Identity
    identity = Level1Identity()
    identity.generate(name=name)
    
    # 2. Create agent.json
    manifest_path = Path.cwd() / "agent.json"
    
    if manifest_path.exists():
        typer.echo(f"Error: {manifest_path} already exists.", err=True)
        raise typer.Exit(code=1)
        
    manifest = AgentManifest(
        opensurity="0.1",
        id=identity.agent_id,
        name=name,
        version="1.0.0",
        capabilities=[
            Capability(
                id="default-capability",
                description="Default capability generated by init"
            )
        ],
        trust=TrustInfo(**identity.to_manifest_fragment()),
        framework=framework,
        contact="team@example.com"
    )
    
    manifest.to_file(manifest_path)
    
    elapsed = time.time() - start_time
    
    # 3. Print output
    typer.echo(f"Successfully initialized agent '{name}' in {elapsed:.3f}s")
    typer.echo(f"Agent ID: {identity.agent_id}")
    typer.echo("Next steps: Edit agent.json to configure your agent's capabilities.")


@app.command()
def register(manifest: Path = typer.Argument(..., help="Path to agent.json")):
    """Registers an agent manifest with the local registry."""
    if not manifest.exists():
        typer.echo(f"Manifest not found: {manifest}", err=True)
        raise typer.Exit(code=1)
        
    try:
        agent_manifest = AgentManifest.from_file(manifest)
        registry = LocalRegistry()
        registry.register(agent_manifest)
        typer.echo(f"Successfully registered agent '{agent_manifest.name}' ({agent_manifest.id})")
    except OSError as e:
        typer.echo(f"Failed to register agent: {e}", err=True)
        raise typer.Exit(code=1)


class RegistryHTTPRequestHandler(BaseHTTPRequestHandler):
    def _send_json(self, data: dict, status: int = 200) -> None:
        response = json.dumps(data).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(response)))
        self.end_headers()
        self.wfile.write(response)

    def do_GET(self) -> None:
        registry = LocalRegistry()
        parsed_path = urlparse(self.path)
        
        if parsed_path.path == "/discover":
            query = parse_qs(parsed_path.query)
            capability_id = query.get("capability_id", [None])[0]
            if not capability_id:
                self._send_json({"error": "Missing capability_id"}, 400)
                return
                
            agents = registry.discover(capability_id)
            self._send_json({"agents": [a.to_dict() for a in agents]})
            return
            
        elif parsed_path.path == "/agents":
            agents = registry.list_all()
            self._send_json({"agents": [a.to_dict() for a in agents]})
            return
            
        self._send_json({"error": "Not found"}, 404)


@registry_app.command("start")
def registry_start(port: int = typer.Option(default_factory=lambda: int(os.environ.get("OPENSURITY_REGISTRY_PORT", "7700")), help="Port to run registry server on")):
    """Starts the local agent registry server."""
    HTTPServer.allow_reuse_address = True
    server = HTTPServer(("localhost", port), RegistryHTTPRequestHandler)
    typer.echo(f"Starting registry server on http://localhost:{port}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        typer.echo("Shutting down registry server...")
        server.server_close()


@log_app.command("show")
def log_show(agent: str = typer.Option(..., help="Agent ID")):
    """Shows the trust log for a specific agent."""
    store = TrustLogStore()
    latest_cid = store.get_latest_cid(agent)
    
    if not latest_cid:
        typer.echo(f"No trust log found for agent {agent}.")
        return

    try:
        chain = store.get_chain(latest_cid)
    except FileNotFoundError as e:
        typer.echo(f"Error reading chain: {e}", err=True)
        return
        
    total_events = len(chain)
    successes = sum(1 for e in chain if e.outcome == "success")
    success_rate = (successes / total_events) * 100 if total_events > 0 else 0.0
    
    capabilities = set(e.capability_used for e in chain)
    first_timestamp = chain[0].timestamp if chain else "N/A"
    last_timestamp = chain[-1].timestamp if chain else "N/A"
    
    # Try verifying the chain with a Level1Identity (assuming local access for now)
    try:
        identity: Identity
        if agent.startswith("did:key:"):
            from opensurity.identity.level2 import Level2Identity
            identity = Level2Identity(agent_id=agent)
        else:
            identity = Level1Identity(agent_id=agent)
        identity.load()
        is_valid = store.verify_chain(latest_cid, identity)
    except (OSError, ValueError) as e:
        typer.secho(f"Warning: Could not load identity to verify chain: {e}", fg=typer.colors.YELLOW)
        is_valid = False

    typer.echo(f"Trust Log for Agent: {agent}")
    typer.echo("-" * 40)
    typer.echo(f"Total Events:     {total_events}")
    typer.echo(f"Success Rate:     {success_rate:.1f}% ({successes}/{total_events})")
    typer.echo(f"Capabilities Used: {', '.join(capabilities)}")
    typer.echo(f"First Event:      {first_timestamp}")
    typer.echo(f"Last Event:       {last_timestamp}")
    typer.echo("-" * 40)
    
    if is_valid:
        typer.echo("Integrity:        [OK] Chain verified successfully.")
    else:
        typer.echo("Integrity:        [FAIL] Chain integrity violation detected!")


@identity_app.command("upgrade")
def identity_upgrade(
    manifest: Path = typer.Option(Path("agent.json"), help="Path to the agent.json manifest"),
    level: str = typer.Option(..., help="Identity level (e.g., did-key)")
):
    """Upgrades an agent's identity to a higher trust level securely."""
    import shutil
    import uuid
    import copy
    from opensurity.identity.level1 import Level1Identity
    from opensurity.identity.level2 import Level2Identity
    from opensurity.manifest import AgentManifest
    from opensurity.log.store import TrustLogStore
    from opensurity.registry.local import LocalRegistry

    if level != "did-key":
        typer.secho(f"Unsupported upgrade level: {level}", fg=typer.colors.RED)
        raise typer.Exit(1)

    if not manifest.exists():
        typer.secho(f"Manifest not found: {manifest}", fg=typer.colors.RED)
        raise typer.Exit(1)

    typer.secho("Initiating Trust Upgrade to L2 (did:key)...", fg=typer.colors.CYAN)

    agent_manifest = AgentManifest.from_file(manifest)
    old_id = agent_manifest.id

    # 1. Backup agent.json + key file + registry.db
    backup_id = uuid.uuid4().hex[:8]
    backup_dir = Path.home() / ".opensurity" / "backups" / backup_id
    backup_dir.mkdir(parents=True, exist_ok=True)

    manifest_backup = backup_dir / "agent.json.bak"
    shutil.copy2(manifest, manifest_backup)

    l1_identity = Level1Identity(agent_id=old_id)
    key_path = l1_identity.key_path
    key_backup = None
    if key_path.exists():
        key_backup = backup_dir / f"{old_id}.key.bak"
        shutil.copy2(key_path, key_backup)

    registry_db = Path.home() / ".opensurity" / "registry.db"
    registry_backup = None
    if registry_db.exists():
        registry_backup = backup_dir / "registry.db.bak"
        shutil.copy2(registry_db, registry_backup)
        
    store = TrustLogStore()
    latest_cid = store.get_latest_cid(old_id)
    events = store.get_chain(latest_cid) if latest_cid else []
    
    log_backup_dir = backup_dir / "logs"
    log_backup_dir.mkdir(parents=True, exist_ok=True)
    if (store.base_dir / old_id).exists():
        for f in (store.base_dir / old_id).glob("*"):
            shutil.copy2(f, log_backup_dir / f.name)

    typer.echo("[1/6] Created atomic backup of all state.")

    # 2. Generate Ed25519 keypair + derive DID
    l2_identity = Level2Identity(agent_id="")
    did, priv_b64 = l2_identity.generate()
    l2_identity.agent_id = did
    l2_identity.save(priv_b64)
    typer.echo(f"[2/6] Generated Ed25519 keypair. Derived DID: {did}")

    try:
        # 3. Re-sign all trust log events into new files
        typer.echo(f"[3/6] Re-signing {len(events)} trust log events...")
        new_events = []
        for e in events:
            new_e = copy.deepcopy(e)
            new_e.agent = did
            if new_e.delegator == old_id:
                new_e.delegator = did
                
            new_e.prev_cid = None
            new_e.signature = ""
            new_events.append(new_e)

        prev_cid = None
        for ne in new_events:
            ne.prev_cid = prev_cid
            ne.sign(l2_identity)
            cid = store.append(ne)
            prev_cid = cid

        old_pointer = store.base_dir / old_id
        if old_pointer.exists():
            shutil.rmtree(old_pointer)

        # 4. Update agent.json
        agent_manifest.id = did
        agent_manifest.trust.level = "did"
        agent_manifest.to_file(manifest)
        typer.echo("[4/6] Updated agent.json with new DID.")

        # 5. Update registry
        registry = LocalRegistry()
        registry.register(agent_manifest)
        typer.echo("[5/6] Updated LocalRegistry.")

        # 6. Delete old key file
        if key_path.exists():
            key_path.unlink()
        typer.echo("[6/6] Deleted old L1 key file.")

        typer.secho("\nUpgrade Complete!", fg=typer.colors.GREEN, bold=True)
        typer.echo(f"New Identity: {did}")

    except (OSError, ValueError) as e:
        typer.secho(f"\n[FATAL] Upgrade failed: {e}", err=True, fg=typer.colors.RED)
        typer.secho("Initiating rollback from backup...", err=True, fg=typer.colors.YELLOW)
        
        shutil.copy2(manifest_backup, manifest)
        
        if key_backup and key_backup.exists():
            shutil.copy2(key_backup, key_path)
            
        if registry_backup and registry_backup.exists():
            shutil.copy2(registry_backup, registry_db)
            
        if (store.base_dir / old_id).exists():
            shutil.rmtree(store.base_dir / old_id)
        (store.base_dir / old_id).mkdir(parents=True, exist_ok=True)
        for f in log_backup_dir.glob("*"):
            shutil.copy2(f, store.base_dir / old_id / f.name)
            
        l2_key_path = l2_identity._get_key_path()
        if l2_key_path.exists():
            l2_key_path.unlink()

        typer.secho("Rollback complete. State restored.", err=True, fg=typer.colors.GREEN)
        raise typer.Exit(1)


@app.command("demo")
def demo_command(
    agents: int = typer.Option(3, help="Number of agents to simulate"),
    registry_port: int = typer.Option(default_factory=lambda: int(os.environ.get("OPENSURITY_REGISTRY_PORT", "7700")), help="Port to run registry server on")
):
    """Runs a complete local demonstration pipeline."""
    from opensurity.cli.demo import run_demo
    run_demo(agents, registry_port)


@app.command()
def verify(manifest: Path = typer.Argument(..., help="Path to agent.json")):
    """Verifies a manifest and identity locally."""
    typer.echo("Not yet implemented: verify")


if __name__ == "__main__":
    app()
